config/routes.rb
QuickOrdering::Application.routes.draw do

  devise_for :users, :controllers => {:users => "users"} do
  end

  resources :restaurants do
    resources :categories

    resources :foods

    resources :orders
  end

  resources :companies

  get 'setting', to: 'users#setting'
  put 'update_setting', to: 'users#update_setting'

  mount Wechat::WechatAPI => '/'

  root :to => 'restaurants#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, 
        :weixin_name, :name, :telephone, :company_id
  # attr_accessible :title, :body

  has_many :orders
  belongs_to :company
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def setting
  end

  def update_setting
    respond_to do |format|
      if current_user.update_attributes(params[:user])
        format.html { redirect_to '/setting', notice: '用户设置已更新.' }
      else
        format.html { render action: "setting" }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/menu/_login_item.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('注销', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('登录', new_user_session_path)  %>  
  </li>
<% end %>

app/views/users/menu/_register_item.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('设置', setting_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('注册', new_user_registration_path)  %>
  </li>
<% end %>